[package]
name = "planchet-stresstest"
version = "0.1.0"
edition = "2021"

[dependencies]
planchet = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
