[package]
name = "planchet-stresstest"
version = "0.1.0"
edition = "2021"

[dependencies]
planchet = { path = "../planchet" }
clap = { version = "4.5.4", features = ["derive", "env"] }
tokio = { version = "1.37.0", features = ["full"] }
anyhow = "1.0.86"
